name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --release --locked
      - name: Package binary
        run: tar -czf matui-${{ matrix.os }}.tar.gz -C target/release matui
      - uses: actions/upload-artifact@v4
        with:
          name: matui-${{ matrix.os }}
          path: matui-${{ matrix.os }}.tar.gz
          retention-days: 7
